#!/usr/bin/env python
from glob import glob
from pathlib import Path

Import('env')

env.Append(CPPPATH=["src/"])
sources = Glob("*.cpp")
sources += Glob("src/*.cpp")
sources += Glob("src/features/*.cpp")
sources += Glob("src/math/*.cpp")
sources += Glob("src/modifiers/*.cpp")
sources += Glob("src/synchronizers/*.cpp")

module_env = env.Clone()
module_env.add_source_files(env.modules_sources, sources)

if env.editor_build:
    module_env.add_source_files(env.modules_sources, "editor/*.cpp")
