name: 🍎 macOS Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: "macos-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Compilation (x86_64)
        uses: ./.github/actions/build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} arch=x86_64
          platform: macos

      - name: Compilation (arm64)
        uses: ./.github/actions/build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} arch=arm64
          platform: macos
